title: Jekyll Course Theme
subtitle: Version 0
lang: en
baseurl: "/jekyll-course-theme"
url: "https://ollpu.github.io"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # For Finnish quotes:
  # smart_quotes: rsquo,rsquo,rdquo,rdquo

permalink: /:title/

collections:
  material:
    output: true
    permalink: /:collection/:title/

hide_other_section_menus: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
